---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-16.04
    run_list:
      - recipe[apt::default]
  - name: ubuntu-14.04
    run_list:
      - recipe[apt::default]
  - name: centos-7.5
    run_list:
      - recipe[yum-epel::default]
  - name: centos-6.8
    run_list:
      - recipe[yum-epel::default]

suites:
  - name: default
    run_list:
      - recipe[collectd::default]
  - name: userchange
    run_list:
      - recipe[collectd::default]
      - recipe[collectd-test::_test_plugin]
    attributes:
      collectd:
        service_user: 'root'
        service_group: 'root'
